# Generated by Django 5.1.3 on 2024-11-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_client_alter_product_price_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
