# Generated by Django 5.1.3 on 2024-11-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingadress',
            options={'verbose_name_plural': 'Adresse Livraison'},
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='addresse',
            new_name='Shipping_addresse',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='city',
            new_name='Shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='email',
            new_name='Shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='full_name',
            new_name='Shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='zipcode',
            new_name='Shipping_zipcode',
        ),
    ]
