# Generated by Django 5.1.3 on 2024-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='shipping_numberphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
