# Generated by Django 5.1.3 on 2024-12-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_shippingadress_shipping_numberphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='shipping_numberphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
